name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: uv sync --all-extras
      
    - name: Run tests with pytest
      run: uv run pytest -v --tb=short
      
    - name: Run ruff format check
      run: uv run ruff format --check .
      
    - name: Run ruff linter
      run: uv run ruff check .
      
    - name: Run type checking with mypy
      run: uv run mypy src/ || true  # Allow mypy to fail for now